
version: '3.4'

services:
  csharpconstructorsthisoverloadingencapsulation:
    image: csharpconstructorsthisoverloadingencapsulation
    build:
      context: .
      dockerfile: ./Dockerfile
