
version: '3.4'

services:
  csharpconstructorsthisoverloadingencapsulation:
    image: csharpconstructorsthisoverloadingencapsulation
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
